<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FoodItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [

            // ══════════════════════════════════════════════════════════════════════
            // NEPALI STAPLES – HEALTHY
            // ══════════════════════════════════════════════════════════════════════
            ['name' => 'Dal Bhat (Rice + Lentils + Tarkari)',  'category' => 'healthy',   'type' => 'homemade',  'calories' => 520,  'unit' => 'plate'],
            ['name' => 'Dhido (Buckwheat Porridge)',           'category' => 'healthy',   'type' => 'homemade',  'calories' => 200,  'unit' => 'bowl'],
            ['name' => 'Phapar Ko Dhido (Buckwheat Dhido)',   'category' => 'healthy',   'type' => 'homemade',  'calories' => 190,  'unit' => 'bowl'],
            ['name' => 'Kodo Ko Dhido (Millet Dhido)',        'category' => 'healthy',   'type' => 'homemade',  'calories' => 195,  'unit' => 'bowl'],
            ['name' => 'Kwati (Nine-Bean Soup)',               'category' => 'healthy',   'type' => 'homemade',  'calories' => 210,  'unit' => 'bowl'],
            ['name' => 'Gundruk Ko Jhol (Fermented Greens Soup)', 'category' => 'healthy','type' => 'homemade', 'calories' => 80,   'unit' => 'bowl'],
            ['name' => 'Chatamari (Nepali Rice Crepe)',        'category' => 'healthy',   'type' => 'homemade',  'calories' => 140,  'unit' => 'piece'],
            ['name' => 'Bara (Newari Lentil Pancake)',         'category' => 'healthy',   'type' => 'homemade',  'calories' => 130,  'unit' => 'piece'],
            ['name' => 'Thukpa (Nepali Noodle Soup)',          'category' => 'healthy',   'type' => 'homemade',  'calories' => 360,  'unit' => 'bowl'],
            ['name' => 'Tingmo (Steamed Tibetan Bread)',       'category' => 'healthy',   'type' => 'homemade',  'calories' => 120,  'unit' => 'piece'],
            ['name' => 'Aloo Tama (Potato & Bamboo Shoot Curry)', 'category' => 'healthy','type' => 'homemade', 'calories' => 180,  'unit' => 'bowl'],
            ['name' => 'Sishnu Ko Jhol (Nettle Soup)',         'category' => 'healthy',   'type' => 'homemade',  'calories' => 70,   'unit' => 'bowl'],
            ['name' => 'Chyura (Beaten Rice)',                 'category' => 'healthy',   'type' => 'homemade',  'calories' => 180,  'unit' => 'bowl'],
            ['name' => 'Samay Baji (Newari Feast Platter)',    'category' => 'healthy',   'type' => 'homemade',  'calories' => 420,  'unit' => 'plate'],
            ['name' => 'Buff Curry (Buffalo Meat Curry)',      'category' => 'healthy',   'type' => 'homemade',  'calories' => 310,  'unit' => 'bowl'],
            ['name' => 'Choila (Spiced Grilled Buffalo)',      'category' => 'healthy',   'type' => 'homemade',  'calories' => 230,  'unit' => 'plate'],
            ['name' => 'Aloo Ko Achar (Nepali Potato Pickle)', 'category' => 'healthy',   'type' => 'homemade',  'calories' => 140,  'unit' => 'bowl'],
            ['name' => 'Golbheda Ko Achar (Tomato Pickle)',   'category' => 'healthy',   'type' => 'homemade',  'calories' => 60,   'unit' => 'bowl'],
            ['name' => 'Phapar Ko Roti (Buckwheat Bread)',    'category' => 'healthy',   'type' => 'homemade',  'calories' => 100,  'unit' => 'piece'],
            ['name' => 'Kodo Ko Roti (Millet Bread)',         'category' => 'healthy',   'type' => 'homemade',  'calories' => 95,   'unit' => 'piece'],
            ['name' => 'Masyaura (Dried Lentil Dumplings)',   'category' => 'healthy',   'type' => 'homemade',  'calories' => 110,  'unit' => 'piece'],
            ['name' => 'Jhol Momo (Momo in Broth)',           'category' => 'healthy',   'type' => 'homemade',  'calories' => 260,  'unit' => 'plate'],

            // ── NEPALI HEALTHY – READYMADE / PRESERVED ───────────────────────────
            ['name' => 'Gundruk (Fermented Leafy Vegetable)', 'category' => 'healthy',   'type' => 'readymade', 'calories' => 45,   'unit' => '100g'],
            ['name' => 'Sinki (Fermented Radish)',            'category' => 'healthy',   'type' => 'readymade', 'calories' => 30,   'unit' => '100g'],
            ['name' => 'Chhurpi (Dried Yak Cheese)',          'category' => 'healthy',   'type' => 'readymade', 'calories' => 90,   'unit' => 'piece'],
            ['name' => 'Sukuti (Dried Buffalo Meat)',         'category' => 'healthy',   'type' => 'readymade', 'calories' => 200,  'unit' => 'serving'],

            // ── NEPALI UNHEALTHY / SWEETS / FRIED ────────────────────────────────
            ['name' => 'Sel Roti (Nepali Rice Ring)',         'category' => 'unhealthy', 'type' => 'junk',      'calories' => 160,  'unit' => 'piece'],
            ['name' => 'Yomari (Sweet Rice Dumpling)',        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 150,  'unit' => 'piece'],
            ['name' => 'Fried Momo',                          'category' => 'unhealthy', 'type' => 'junk',      'calories' => 290,  'unit' => 'plate'],
            ['name' => 'C-Momo (Momo in Creamy Sauce)',      'category' => 'unhealthy', 'type' => 'junk',      'calories' => 320,  'unit' => 'plate'],
            ['name' => 'Juju Dhau (Bhaktapur Sweetened Yogurt)', 'category' => 'unhealthy','type' => 'junk',   'calories' => 140,  'unit' => 'bowl'],
            ['name' => 'Lakhamari (Newari Fried Sweet Bread)','category' => 'unhealthy', 'type' => 'junk',      'calories' => 220,  'unit' => 'piece'],
            ['name' => 'Sikarni (Spiced Sweet Yogurt)',       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 240,  'unit' => 'bowl'],
            ['name' => 'Chaku (Nepali Molasses Sweet)',       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 130,  'unit' => 'piece'],
            ['name' => 'Haluwa (Nepali Sesame Sweet)',        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 280,  'unit' => 'piece'],
            ['name' => 'Nepali Kheer (Rice Pudding)',         'category' => 'unhealthy', 'type' => 'junk',      'calories' => 260,  'unit' => 'bowl'],
            ['name' => 'Wai Wai Noodles (Packaged)',          'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 340,  'unit' => 'pack'],
            ['name' => 'Chau Chau Noodles (Packaged)',        'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 330,  'unit' => 'pack'],

            // ── NEPALI DRINKS ─────────────────────────────────────────────────────
            ['name' => 'Masala Chiya (Nepali Spiced Tea)',   'category' => 'healthy',   'type' => 'drink',     'calories' => 60,   'unit' => 'cup'],
            ['name' => 'Tongba (Millet Hot Beer)',            'category' => 'unhealthy', 'type' => 'drink',     'calories' => 120,  'unit' => 'glass'],
            ['name' => 'Raksi (Nepali Distilled Spirit)',    'category' => 'unhealthy', 'type' => 'drink',     'calories' => 90,   'unit' => 'glass'],
            ['name' => 'Aila (Newari Rice Wine)',             'category' => 'unhealthy', 'type' => 'drink',     'calories' => 100,  'unit' => 'glass'],
            ['name' => 'Chhang (Fermented Grain Beer)',      'category' => 'unhealthy', 'type' => 'drink',     'calories' => 110,  'unit' => 'glass'],

            // ══════════════════════════════════════════════════════════════════════
            // NORTH INDIA – HEALTHY
            // ══════════════════════════════════════════════════════════════════════
            ['name' => 'Makki di Roti (Cornmeal Flatbread)',  'category' => 'healthy',   'type' => 'homemade',  'calories' => 130,  'unit' => 'piece'],
            ['name' => 'Sarson da Saag (Mustard Greens)',     'category' => 'healthy',   'type' => 'homemade',  'calories' => 140,  'unit' => 'bowl'],
            ['name' => 'Matar Paneer',                        'category' => 'healthy',   'type' => 'homemade',  'calories' => 260,  'unit' => 'bowl'],
            ['name' => 'Aloo Mutter (Potato Pea Curry)',     'category' => 'healthy',   'type' => 'homemade',  'calories' => 180,  'unit' => 'bowl'],
            ['name' => 'Yakhni Pulao (Broth-cooked Rice)',   'category' => 'healthy',   'type' => 'homemade',  'calories' => 310,  'unit' => 'plate'],
            ['name' => 'Haleem (Lentil-Wheat-Meat Stew)',    'category' => 'healthy',   'type' => 'homemade',  'calories' => 290,  'unit' => 'bowl'],
            ['name' => 'Paya Soup (Trotters Bone Broth)',    'category' => 'healthy',   'type' => 'homemade',  'calories' => 160,  'unit' => 'bowl'],
            ['name' => 'Rumali Roti',                         'category' => 'healthy',   'type' => 'homemade',  'calories' => 90,   'unit' => 'piece'],
            ['name' => 'Missi Roti (Besan-Wheat Roti)',      'category' => 'healthy',   'type' => 'homemade',  'calories' => 115,  'unit' => 'piece'],
            ['name' => 'Kashmiri Kahwa (Saffron Tea)',       'category' => 'healthy',   'type' => 'drink',     'calories' => 30,   'unit' => 'cup'],
            ['name' => 'Sheer Chai (Pink Salt Tea)',          'category' => 'healthy',   'type' => 'drink',     'calories' => 80,   'unit' => 'cup'],
            ['name' => 'Singhara Atta Roti (Water Chestnut)','category' => 'healthy',   'type' => 'homemade',  'calories' => 105,  'unit' => 'piece'],
            ['name' => 'Amaranth (Rajgira) Roti',            'category' => 'healthy',   'type' => 'homemade',  'calories' => 100,  'unit' => 'piece'],
            ['name' => 'Sabudana Khichdi',                   'category' => 'healthy',   'type' => 'homemade',  'calories' => 250,  'unit' => 'plate'],
            ['name' => 'Adraki Lamb Chops (Grilled)',        'category' => 'healthy',   'type' => 'homemade',  'calories' => 280,  'unit' => 'piece'],
            ['name' => 'Chicken Keema (Dry)',                 'category' => 'healthy',   'type' => 'homemade',  'calories' => 240,  'unit' => 'plate'],

            // ── NORTH INDIA – UNHEALTHY ───────────────────────────────────────────
            ['name' => 'Kadhi Pakora',                        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 310,  'unit' => 'bowl'],
            ['name' => 'Dal Baati Churma',                    'category' => 'unhealthy', 'type' => 'junk',      'calories' => 560,  'unit' => 'plate'],
            ['name' => 'Laal Maas (Rajasthani Mutton)',      'category' => 'unhealthy', 'type' => 'junk',      'calories' => 420,  'unit' => 'bowl'],
            ['name' => 'Rogan Josh (Kashmiri Lamb)',          'category' => 'unhealthy', 'type' => 'junk',      'calories' => 390,  'unit' => 'bowl'],
            ['name' => 'Kashmiri Dum Aloo',                  'category' => 'unhealthy', 'type' => 'junk',      'calories' => 280,  'unit' => 'bowl'],
            ['name' => 'Nihari (Slow-cooked Lamb Stew)',     'category' => 'unhealthy', 'type' => 'junk',      'calories' => 450,  'unit' => 'bowl'],
            ['name' => 'Achari Gosht',                        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 400,  'unit' => 'bowl'],
            ['name' => 'Shahi Paneer',                        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 380,  'unit' => 'bowl'],
            ['name' => 'Kulcha',                              'category' => 'unhealthy', 'type' => 'junk',      'calories' => 210,  'unit' => 'piece'],
            ['name' => 'Amritsari Kulcha',                   'category' => 'unhealthy', 'type' => 'junk',      'calories' => 280,  'unit' => 'piece'],
            ['name' => 'Puri (Deep Fried Bread)',             'category' => 'unhealthy', 'type' => 'junk',      'calories' => 140,  'unit' => 'piece'],
            ['name' => 'Paratha (Plain with Ghee)',           'category' => 'unhealthy', 'type' => 'junk',      'calories' => 250,  'unit' => 'piece'],
            ['name' => 'Gobi Paratha',                        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 290,  'unit' => 'piece'],
            ['name' => 'Pyaaz Paratha (Onion Paratha)',      'category' => 'unhealthy', 'type' => 'junk',      'calories' => 270,  'unit' => 'piece'],
            ['name' => 'Paneer Paratha',                      'category' => 'unhealthy', 'type' => 'junk',      'calories' => 320,  'unit' => 'piece'],
            ['name' => 'Lachha Paratha',                     'category' => 'unhealthy', 'type' => 'junk',      'calories' => 260,  'unit' => 'piece'],
            ['name' => 'Gajar Halwa (Carrot Halwa)',         'category' => 'unhealthy', 'type' => 'junk',      'calories' => 290,  'unit' => 'bowl'],
            ['name' => 'Sooji Halwa (Semolina Halwa)',       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 320,  'unit' => 'bowl'],
            ['name' => 'Moong Dal Halwa',                    'category' => 'unhealthy', 'type' => 'junk',      'calories' => 380,  'unit' => 'bowl'],
            ['name' => 'Pinni (Punjabi Wheat-Ghee Sweet)',   'category' => 'unhealthy', 'type' => 'junk',      'calories' => 260,  'unit' => 'piece'],
            ['name' => 'Gajrela (Carrot-Rice Pudding)',      'category' => 'unhealthy', 'type' => 'junk',      'calories' => 280,  'unit' => 'bowl'],
            ['name' => 'Kheer (Rice Pudding)',               'category' => 'unhealthy', 'type' => 'junk',      'calories' => 260,  'unit' => 'bowl'],
            ['name' => 'Phirni (Creamy Rice Pudding)',       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 240,  'unit' => 'bowl'],
            ['name' => 'Shahi Tukda (Bread Pudding)',        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 370,  'unit' => 'piece'],
            ['name' => 'Kaju Katli (Cashew Fudge)',          'category' => 'unhealthy', 'type' => 'junk',      'calories' => 180,  'unit' => 'piece'],
            ['name' => 'Peda',                               'category' => 'unhealthy', 'type' => 'junk',      'calories' => 110,  'unit' => 'piece'],
            ['name' => 'Kalakand (Milk Cake)',               'category' => 'unhealthy', 'type' => 'junk',      'calories' => 200,  'unit' => 'piece'],
            ['name' => 'Imarti',                             'category' => 'unhealthy', 'type' => 'junk',      'calories' => 210,  'unit' => 'piece'],
            ['name' => 'Balushahi',                          'category' => 'unhealthy', 'type' => 'junk',      'calories' => 200,  'unit' => 'piece'],
            ['name' => 'Mawa Jalebi',                        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 280,  'unit' => 'piece'],
            ['name' => 'Cham Cham (Bengali Sweet)',          'category' => 'unhealthy', 'type' => 'junk',      'calories' => 180,  'unit' => 'piece'],
            ['name' => 'Chicken Biryani (Restaurant)',       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 520,  'unit' => 'plate'],
            ['name' => 'Veg Biryani (Restaurant)',           'category' => 'unhealthy', 'type' => 'junk',      'calories' => 420,  'unit' => 'plate'],
            ['name' => 'Egg Biryani',                        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 480,  'unit' => 'plate'],
            ['name' => 'Mutton Biryani',                     'category' => 'unhealthy', 'type' => 'junk',      'calories' => 560,  'unit' => 'plate'],
            ['name' => 'Prawn Biryani',                      'category' => 'unhealthy', 'type' => 'junk',      'calories' => 490,  'unit' => 'plate'],
            ['name' => 'Fish Biryani',                       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 470,  'unit' => 'plate'],

            // ── STREET FOOD (INDIA – NORTH) ───────────────────────────────────────
            ['name' => 'Kachori',                            'category' => 'unhealthy', 'type' => 'junk',      'calories' => 220,  'unit' => 'piece'],
            ['name' => 'Pyaaz Kachori (Onion Kachori)',      'category' => 'unhealthy', 'type' => 'junk',      'calories' => 240,  'unit' => 'piece'],
            ['name' => 'Dal Kachori',                        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 230,  'unit' => 'piece'],
            ['name' => 'Bread Pakora',                       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 260,  'unit' => 'piece'],
            ['name' => 'Onion Pakora / Bhajia',              'category' => 'unhealthy', 'type' => 'junk',      'calories' => 200,  'unit' => 'plate'],
            ['name' => 'Paneer Pakora',                      'category' => 'unhealthy', 'type' => 'junk',      'calories' => 280,  'unit' => 'plate'],
            ['name' => 'Palak Pakora',                       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 180,  'unit' => 'plate'],
            ['name' => 'Egg Kathi Roll (Frankie)',           'category' => 'unhealthy', 'type' => 'junk',      'calories' => 380,  'unit' => 'piece'],
            ['name' => 'Chicken Frankie',                    'category' => 'unhealthy', 'type' => 'junk',      'calories' => 420,  'unit' => 'piece'],
            ['name' => 'Mutton Roll',                        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 450,  'unit' => 'piece'],
            ['name' => 'Dabeli (Kutchi Burger)',             'category' => 'unhealthy', 'type' => 'junk',      'calories' => 280,  'unit' => 'piece'],
            ['name' => 'Ragda Patties',                      'category' => 'unhealthy', 'type' => 'junk',      'calories' => 320,  'unit' => 'plate'],
            ['name' => 'Gobi Manchurian',                    'category' => 'unhealthy', 'type' => 'junk',      'calories' => 250,  'unit' => 'plate'],
            ['name' => 'Chilli Paneer',                      'category' => 'unhealthy', 'type' => 'junk',      'calories' => 320,  'unit' => 'plate'],
            ['name' => 'Mushroom Manchurian',                'category' => 'unhealthy', 'type' => 'junk',      'calories' => 230,  'unit' => 'plate'],
            ['name' => 'Chicken Manchurian',                 'category' => 'unhealthy', 'type' => 'junk',      'calories' => 350,  'unit' => 'plate'],
            ['name' => 'Schezwan Fried Rice',                'category' => 'unhealthy', 'type' => 'junk',      'calories' => 480,  'unit' => 'plate'],
            ['name' => 'Hakka Noodles',                      'category' => 'unhealthy', 'type' => 'junk',      'calories' => 420,  'unit' => 'plate'],
            ['name' => 'Schezwan Noodles',                   'category' => 'unhealthy', 'type' => 'junk',      'calories' => 440,  'unit' => 'plate'],
            ['name' => 'Mysore Pak',                         'category' => 'unhealthy', 'type' => 'junk',      'calories' => 220,  'unit' => 'piece'],

            // ══════════════════════════════════════════════════════════════════════
            // SOUTH INDIA – HEALTHY
            // ══════════════════════════════════════════════════════════════════════
            ['name' => 'Curd Rice (Thayir Sadam)',           'category' => 'healthy',   'type' => 'homemade',  'calories' => 230,  'unit' => 'plate'],
            ['name' => 'Ven Pongal (Savory Rice-Lentil)',    'category' => 'healthy',   'type' => 'homemade',  'calories' => 280,  'unit' => 'plate'],
            ['name' => 'Aviyal (Mixed Vegetable Coconut)',   'category' => 'healthy',   'type' => 'homemade',  'calories' => 160,  'unit' => 'bowl'],
            ['name' => 'Puttu (Steamed Rice Flour Cylinders)','category' => 'healthy',  'type' => 'homemade',  'calories' => 200,  'unit' => 'piece'],
            ['name' => 'Appam (Fermented Rice Crepe)',       'category' => 'healthy',   'type' => 'homemade',  'calories' => 120,  'unit' => 'piece'],
            ['name' => 'Idiyappam (String Hoppers)',         'category' => 'healthy',   'type' => 'homemade',  'calories' => 150,  'unit' => 'plate'],
            ['name' => 'Kerala Fish Curry (Coconut)',        'category' => 'healthy',   'type' => 'homemade',  'calories' => 270,  'unit' => 'bowl'],
            ['name' => 'Meen Kuzhambu (Tamarind Fish Curry)','category' => 'healthy',  'type' => 'homemade',  'calories' => 250,  'unit' => 'bowl'],
            ['name' => 'Karimeen Pollichathu (Pearl Spot Fish)','category' => 'healthy','type' => 'homemade',  'calories' => 240,  'unit' => 'piece'],
            ['name' => 'Kozhi Curry (Kerala Chicken)',       'category' => 'healthy',   'type' => 'homemade',  'calories' => 280,  'unit' => 'bowl'],
            ['name' => 'Kozhukattai (Steamed Rice Dumplings)','category' => 'healthy',  'type' => 'homemade',  'calories' => 130,  'unit' => 'piece'],
            ['name' => 'Erissery (Pumpkin & Coconut)',       'category' => 'healthy',   'type' => 'homemade',  'calories' => 170,  'unit' => 'bowl'],
            ['name' => 'Thoran (Kerala Stir-fried Vegetable)','category' => 'healthy',  'type' => 'homemade',  'calories' => 100,  'unit' => 'bowl'],
            ['name' => 'Olan (Winter Melon in Coconut Milk)','category' => 'healthy',   'type' => 'homemade',  'calories' => 120,  'unit' => 'bowl'],
            ['name' => 'Kalan (Yam-Coconut-Yogurt Curry)',  'category' => 'healthy',   'type' => 'homemade',  'calories' => 150,  'unit' => 'bowl'],
            ['name' => 'Kootu (Vegetable-Lentil-Coconut)',  'category' => 'healthy',   'type' => 'homemade',  'calories' => 160,  'unit' => 'bowl'],
            ['name' => 'Bisi Bele Bath (Karnataka)',         'category' => 'healthy',   'type' => 'homemade',  'calories' => 300,  'unit' => 'plate'],
            ['name' => 'Akki Roti (Rice Flour Bread)',       'category' => 'healthy',   'type' => 'homemade',  'calories' => 120,  'unit' => 'piece'],
            ['name' => 'Neer Dosa (Thin Rice Crepe)',        'category' => 'healthy',   'type' => 'homemade',  'calories' => 80,   'unit' => 'piece'],
            ['name' => 'Paper Dosa',                         'category' => 'healthy',   'type' => 'homemade',  'calories' => 100,  'unit' => 'piece'],
            ['name' => 'Amboli (Fermented Rice Pancake)',    'category' => 'healthy',   'type' => 'homemade',  'calories' => 130,  'unit' => 'piece'],
            ['name' => 'Shorshe Ilish (Hilsa in Mustard)',  'category' => 'healthy',   'type' => 'homemade',  'calories' => 290,  'unit' => 'plate'],
            ['name' => 'Macher Jhol (Bengali Fish Curry)',  'category' => 'healthy',   'type' => 'homemade',  'calories' => 230,  'unit' => 'bowl'],
            ['name' => 'Aloo Posto (Potato in Poppy Seed)', 'category' => 'healthy',   'type' => 'homemade',  'calories' => 190,  'unit' => 'bowl'],
            ['name' => 'Chingri Malai Curry (Prawn Coconut)','category' => 'healthy',  'type' => 'homemade',  'calories' => 260,  'unit' => 'bowl'],
            ['name' => 'Shukto (Bengali Bitter Vegetable Medley)','category' => 'healthy','type' => 'homemade','calories' => 130,  'unit' => 'bowl'],
            ['name' => 'Masor Tenga (Assamese Sour Fish)',  'category' => 'healthy',   'type' => 'homemade',  'calories' => 200,  'unit' => 'bowl'],
            ['name' => 'Aloo Pitika (Assamese Mashed Potato)','category' => 'healthy',  'type' => 'homemade',  'calories' => 120,  'unit' => 'bowl'],
            ['name' => 'Panta Bhat (Fermented Rice)',        'category' => 'healthy',   'type' => 'homemade',  'calories' => 180,  'unit' => 'plate'],

            // ── SOUTH/EAST INDIA – UNHEALTHY ──────────────────────────────────────
            ['name' => 'Masala Dosa',                        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 300,  'unit' => 'piece'],
            ['name' => 'Rava Dosa',                          'category' => 'unhealthy', 'type' => 'junk',      'calories' => 220,  'unit' => 'piece'],
            ['name' => 'Mysore Masala Dosa',                 'category' => 'unhealthy', 'type' => 'junk',      'calories' => 330,  'unit' => 'piece'],
            ['name' => 'Medu Vada (Deep Fried Lentil Donut)','category' => 'unhealthy', 'type' => 'junk',      'calories' => 190,  'unit' => 'piece'],
            ['name' => 'Paal Payasam (Milk Rice Pudding)',   'category' => 'unhealthy', 'type' => 'junk',      'calories' => 250,  'unit' => 'bowl'],
            ['name' => 'Murukku (Fried Rice-Lentil Snack)', 'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 170,  'unit' => 'handful'],
            ['name' => 'Chakli (Fried Spiral Snack)',        'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 160,  'unit' => 'handful'],
            ['name' => 'Chettinad Chicken Curry',            'category' => 'unhealthy', 'type' => 'junk',      'calories' => 380,  'unit' => 'bowl'],
            ['name' => 'Luchi (Bengali Fried Bread)',        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 140,  'unit' => 'piece'],
            ['name' => 'Kosha Mangsho (Slow-cooked Mutton)', 'category' => 'unhealthy', 'type' => 'junk',      'calories' => 420,  'unit' => 'bowl'],
            ['name' => 'Rasgulla',                           'category' => 'unhealthy', 'type' => 'junk',      'calories' => 130,  'unit' => 'piece'],
            ['name' => 'Sandesh (Bengali Chhena Sweet)',     'category' => 'unhealthy', 'type' => 'junk',      'calories' => 120,  'unit' => 'piece'],
            ['name' => 'Mishti Doi (Sweetened Yogurt)',      'category' => 'unhealthy', 'type' => 'junk',      'calories' => 160,  'unit' => 'bowl'],
            ['name' => 'Pantua (Bengali Fried Sweet)',       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 190,  'unit' => 'piece'],
            ['name' => 'Chenna Poda (Odia Baked Cheese Sweet)','category' => 'unhealthy','type' => 'junk',     'calories' => 200,  'unit' => 'piece'],
            ['name' => 'Begun Bhaja (Fried Eggplant)',       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 130,  'unit' => 'piece'],
            ['name' => 'Pitha (Assamese Rice Cake)',         'category' => 'unhealthy', 'type' => 'junk',      'calories' => 170,  'unit' => 'piece'],
            ['name' => 'Rava Kesari (Semolina Sweet)',       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 260,  'unit' => 'bowl'],

            // ══════════════════════════════════════════════════════════════════════
            // WEST INDIA – HEALTHY
            // ══════════════════════════════════════════════════════════════════════
            ['name' => 'Dhokla (Steamed Fermented Gram Cake)','category' => 'healthy',  'type' => 'homemade',  'calories' => 140,  'unit' => 'plate'],
            ['name' => 'Handvo (Savory Rice-Lentil Cake)',  'category' => 'healthy',   'type' => 'homemade',  'calories' => 200,  'unit' => 'slice'],
            ['name' => 'Khandvi (Rolled Gram Flour)',        'category' => 'healthy',   'type' => 'homemade',  'calories' => 120,  'unit' => 'plate'],
            ['name' => 'Undhiyu (Mixed Winter Vegetable)',  'category' => 'healthy',   'type' => 'homemade',  'calories' => 210,  'unit' => 'bowl'],
            ['name' => 'Aamti (Maharashtrian Tangy Dal)',   'category' => 'healthy',   'type' => 'homemade',  'calories' => 170,  'unit' => 'bowl'],
            ['name' => 'Zunka (Dry Besan Curry)',            'category' => 'healthy',   'type' => 'homemade',  'calories' => 150,  'unit' => 'plate'],
            ['name' => 'Thalipeeth (Multigrain Flatbread)', 'category' => 'healthy',   'type' => 'homemade',  'calories' => 180,  'unit' => 'piece'],
            ['name' => 'Goan Fish Curry',                   'category' => 'healthy',   'type' => 'homemade',  'calories' => 250,  'unit' => 'bowl'],
            ['name' => 'Sol Kadhi (Kokum Coconut Drink)',   'category' => 'healthy',   'type' => 'drink',     'calories' => 50,   'unit' => 'glass'],
            ['name' => 'Gujarati Thali',                    'category' => 'healthy',   'type' => 'homemade',  'calories' => 550,  'unit' => 'plate'],
            ['name' => 'Muthia (Gujarati Steamed Dumplings)','category' => 'healthy',  'type' => 'homemade',  'calories' => 160,  'unit' => 'plate'],
            ['name' => 'Surti Locho',                       'category' => 'healthy',   'type' => 'homemade',  'calories' => 140,  'unit' => 'plate'],

            // ── WEST INDIA – UNHEALTHY ────────────────────────────────────────────
            ['name' => 'Misal Pav (Spicy Sprout Curry & Bread)','category' => 'unhealthy','type' => 'junk',   'calories' => 430,  'unit' => 'plate'],
            ['name' => 'Modak (Steamed Sweet Dumpling)',     'category' => 'unhealthy', 'type' => 'junk',      'calories' => 140,  'unit' => 'piece'],
            ['name' => 'Fried Modak',                        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 180,  'unit' => 'piece'],
            ['name' => 'Puran Poli (Sweet Lentil Flatbread)','category' => 'unhealthy', 'type' => 'junk',      'calories' => 260,  'unit' => 'piece'],
            ['name' => 'Mohanthal (Gujarati Gram Fudge)',   'category' => 'unhealthy', 'type' => 'junk',      'calories' => 280,  'unit' => 'piece'],
            ['name' => 'Goan Pork Vindaloo',                'category' => 'unhealthy', 'type' => 'junk',      'calories' => 430,  'unit' => 'bowl'],
            ['name' => 'Bebinca (Layered Goan Coconut Cake)','category' => 'unhealthy', 'type' => 'junk',     'calories' => 300,  'unit' => 'slice'],
            ['name' => 'Sorpotel (Goan Pork Curry)',        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 400,  'unit' => 'bowl'],
            ['name' => 'Prawn Balchão (Goan Pickled Prawn)','category' => 'unhealthy', 'type' => 'junk',      'calories' => 250,  'unit' => 'bowl'],

            // ══════════════════════════════════════════════════════════════════════
            // MORE INDIAN HEALTHY – DISHES & DRINKS
            // ══════════════════════════════════════════════════════════════════════
            ['name' => 'Sugarcane Juice',                   'category' => 'healthy',   'type' => 'drink',     'calories' => 110,  'unit' => 'glass'],
            ['name' => 'Kanji (Fermented Black Carrot)',    'category' => 'healthy',   'type' => 'drink',     'calories' => 40,   'unit' => 'glass'],
            ['name' => 'Kokum Sherbet',                     'category' => 'healthy',   'type' => 'drink',     'calories' => 60,   'unit' => 'glass'],
            ['name' => 'Bael Sherbet (Wood Apple Drink)',   'category' => 'healthy',   'type' => 'drink',     'calories' => 80,   'unit' => 'glass'],
            ['name' => 'Herbal Kadha (Immunity Drink)',     'category' => 'healthy',   'type' => 'drink',     'calories' => 15,   'unit' => 'cup'],
            ['name' => 'Masala Lemonade',                   'category' => 'healthy',   'type' => 'drink',     'calories' => 40,   'unit' => 'glass'],
            ['name' => 'Jal Zeera',                         'category' => 'healthy',   'type' => 'drink',     'calories' => 20,   'unit' => 'glass'],
            ['name' => 'Rooh Afza Sharbat (Diluted)',       'category' => 'unhealthy', 'type' => 'drink',     'calories' => 90,   'unit' => 'glass'],
            ['name' => 'Thandai (Spiced Milk Drink)',       'category' => 'unhealthy', 'type' => 'drink',     'calories' => 200,  'unit' => 'glass'],
            ['name' => 'Rose Milk (Sweetened)',             'category' => 'unhealthy', 'type' => 'drink',     'calories' => 180,  'unit' => 'glass'],
            ['name' => 'Badam Milk (Almond Milk Sweet)',    'category' => 'unhealthy', 'type' => 'drink',     'calories' => 220,  'unit' => 'glass'],
            ['name' => 'Pista Milk',                        'category' => 'unhealthy', 'type' => 'drink',     'calories' => 230,  'unit' => 'glass'],
            ['name' => 'Kesar Milk (Saffron Milk)',         'category' => 'unhealthy', 'type' => 'drink',     'calories' => 180,  'unit' => 'glass'],
            ['name' => 'Nannari Sherbet',                   'category' => 'healthy',   'type' => 'drink',     'calories' => 70,   'unit' => 'glass'],
            ['name' => 'Paan Sherbet',                      'category' => 'unhealthy', 'type' => 'drink',     'calories' => 100,  'unit' => 'glass'],

            // ── MORE HEALTHY DISHES ───────────────────────────────────────────────
            ['name' => 'Saag (Leafy Green Curry)',          'category' => 'healthy',   'type' => 'homemade',  'calories' => 130,  'unit' => 'bowl'],
            ['name' => 'Moong Dal Chaat',                   'category' => 'healthy',   'type' => 'homemade',  'calories' => 160,  'unit' => 'bowl'],
            ['name' => 'Sprouts Moong Chaat',               'category' => 'healthy',   'type' => 'homemade',  'calories' => 140,  'unit' => 'bowl'],
            ['name' => 'Kala Chana (Black Chickpea Curry)', 'category' => 'healthy',   'type' => 'homemade',  'calories' => 200,  'unit' => 'bowl'],
            ['name' => 'Lobia Curry (Black-Eyed Peas)',     'category' => 'healthy',   'type' => 'homemade',  'calories' => 190,  'unit' => 'bowl'],
            ['name' => 'Tinda Sabzi (Apple Gourd)',         'category' => 'healthy',   'type' => 'homemade',  'calories' => 70,   'unit' => 'bowl'],
            ['name' => 'Parwal Sabzi (Pointed Gourd)',      'category' => 'healthy',   'type' => 'homemade',  'calories' => 80,   'unit' => 'bowl'],
            ['name' => 'Kathal Curry (Jackfruit)',          'category' => 'healthy',   'type' => 'homemade',  'calories' => 150,  'unit' => 'bowl'],
            ['name' => 'Arbi Sabzi (Colocasia)',            'category' => 'healthy',   'type' => 'homemade',  'calories' => 120,  'unit' => 'bowl'],
            ['name' => 'Suran Sabzi (Yam Curry)',           'category' => 'healthy',   'type' => 'homemade',  'calories' => 130,  'unit' => 'bowl'],
            ['name' => 'Dahi Bhaat (Curd Rice)',            'category' => 'healthy',   'type' => 'homemade',  'calories' => 230,  'unit' => 'plate'],
            ['name' => 'Nimona (Green Pea Curry)',          'category' => 'healthy',   'type' => 'homemade',  'calories' => 160,  'unit' => 'bowl'],
            ['name' => 'Sarson Saag Palak Mix',             'category' => 'healthy',   'type' => 'homemade',  'calories' => 120,  'unit' => 'bowl'],
            ['name' => 'Egg Masala',                        'category' => 'healthy',   'type' => 'homemade',  'calories' => 200,  'unit' => 'plate'],
            ['name' => 'Mutton Keema',                      'category' => 'healthy',   'type' => 'homemade',  'calories' => 270,  'unit' => 'plate'],
            ['name' => 'Chicken Keema Matar',               'category' => 'healthy',   'type' => 'homemade',  'calories' => 260,  'unit' => 'plate'],
            ['name' => 'Rohu Fish Fry',                     'category' => 'healthy',   'type' => 'homemade',  'calories' => 180,  'unit' => 'piece'],
            ['name' => 'Surmai (King Fish) Curry',          'category' => 'healthy',   'type' => 'homemade',  'calories' => 260,  'unit' => 'bowl'],
            ['name' => 'Bombil Fry (Bombay Duck)',          'category' => 'healthy',   'type' => 'homemade',  'calories' => 160,  'unit' => 'piece'],
            ['name' => 'Chicken Soup (Desi)',               'category' => 'healthy',   'type' => 'homemade',  'calories' => 130,  'unit' => 'bowl'],
            ['name' => 'Jolpaan (Assamese Breakfast Platter)','category' => 'healthy', 'type' => 'homemade',  'calories' => 280,  'unit' => 'plate'],

            // ── MORE UNHEALTHY / SWEETS ───────────────────────────────────────────
            ['name' => 'Gajar Murabba (Carrot Preserve)',   'category' => 'unhealthy', 'type' => 'junk',      'calories' => 120,  'unit' => 'piece'],
            ['name' => 'Til Gajak (Sesame-Jaggery Bar)',   'category' => 'unhealthy', 'type' => 'junk',      'calories' => 180,  'unit' => 'piece'],
            ['name' => 'Peanut Chikki',                     'category' => 'unhealthy', 'type' => 'junk',      'calories' => 200,  'unit' => 'piece'],
            ['name' => 'Til Chikki (Sesame Brittle)',       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 180,  'unit' => 'piece'],
            ['name' => 'Coconut Ladoo',                     'category' => 'unhealthy', 'type' => 'junk',      'calories' => 160,  'unit' => 'piece'],
            ['name' => 'Dry Fruit Barfi',                   'category' => 'unhealthy', 'type' => 'junk',      'calories' => 200,  'unit' => 'piece'],
            ['name' => 'Besan Ladoo',                       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 180,  'unit' => 'piece'],
            ['name' => 'Rava Ladoo',                        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 160,  'unit' => 'piece'],
            ['name' => 'Nariyal Barfi (Coconut Fudge)',     'category' => 'unhealthy', 'type' => 'junk',      'calories' => 170,  'unit' => 'piece'],
            ['name' => 'Dhokla Sandwich (Fried)',           'category' => 'unhealthy', 'type' => 'junk',      'calories' => 220,  'unit' => 'plate'],
            ['name' => 'Samosa Chaat',                      'category' => 'unhealthy', 'type' => 'junk',      'calories' => 340,  'unit' => 'plate'],
            ['name' => 'Papdi Chaat',                       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 280,  'unit' => 'plate'],
            ['name' => 'Aloo Chaat',                        'category' => 'unhealthy', 'type' => 'junk',      'calories' => 250,  'unit' => 'plate'],
            ['name' => 'Dahi Vada',                         'category' => 'unhealthy', 'type' => 'junk',      'calories' => 260,  'unit' => 'plate'],
            ['name' => 'Raj Kachori',                       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 380,  'unit' => 'piece'],
            ['name' => 'Bonda (Deep Fried Potato Ball)',    'category' => 'unhealthy', 'type' => 'junk',      'calories' => 180,  'unit' => 'piece'],
            ['name' => 'Bread Roll (Fried)',                'category' => 'unhealthy', 'type' => 'junk',      'calories' => 200,  'unit' => 'piece'],
            ['name' => 'Golgappa / Puchka',                 'category' => 'unhealthy', 'type' => 'junk',      'calories' => 160,  'unit' => 'plate'],
            ['name' => 'Corn Bhel',                         'category' => 'unhealthy', 'type' => 'junk',      'calories' => 190,  'unit' => 'plate'],
            ['name' => 'Palak Chaat',                       'category' => 'unhealthy', 'type' => 'junk',      'calories' => 210,  'unit' => 'plate'],
            ['name' => 'Paneer Tikka Masala',               'category' => 'unhealthy', 'type' => 'junk',      'calories' => 420,  'unit' => 'bowl'],
            ['name' => 'Dhaba Chicken Curry',               'category' => 'unhealthy', 'type' => 'junk',      'calories' => 440,  'unit' => 'bowl'],
            ['name' => 'Keema Pav',                         'category' => 'unhealthy', 'type' => 'junk',      'calories' => 450,  'unit' => 'plate'],
            ['name' => 'Egg Pav Bhaji',                     'category' => 'unhealthy', 'type' => 'junk',      'calories' => 420,  'unit' => 'plate'],
            ['name' => 'Paneer Pav Bhaji',                  'category' => 'unhealthy', 'type' => 'junk',      'calories' => 440,  'unit' => 'plate'],
            ['name' => 'Kolhapuri Chicken',                 'category' => 'unhealthy', 'type' => 'junk',      'calories' => 400,  'unit' => 'bowl'],
            ['name' => 'Butter Masala Dosa',                'category' => 'unhealthy', 'type' => 'junk',      'calories' => 380,  'unit' => 'piece'],
            ['name' => 'Ghee Rice',                         'category' => 'unhealthy', 'type' => 'junk',      'calories' => 350,  'unit' => 'plate'],

            // ── PACKAGED INDIA/NEPAL SPECIFIC ─────────────────────────────────────
            ['name' => 'Haldiram Bhujia',                   'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 140,  'unit' => 'pack'],
            ['name' => 'Kurkure',                           'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 130,  'unit' => 'pack'],
            ['name' => 'Bikis Biscuit',                     'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 120,  'unit' => 'pack'],
            ['name' => 'Parle-G Biscuit',                   'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 130,  'unit' => 'pack'],
            ['name' => 'Monaco Salted Crackers',            'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 110,  'unit' => 'pack'],
            ['name' => 'Lay\'s Chips (Indian Masala)',      'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 150,  'unit' => 'pack'],
            ['name' => 'Good Day Biscuits',                 'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 140,  'unit' => 'pack'],
            ['name' => 'Hide & Seek Biscuits',              'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 150,  'unit' => 'pack'],
            ['name' => 'Haldiram Namkeen Mix',              'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 160,  'unit' => 'pack'],
            ['name' => 'Ready Dal Makhani (Packaged)',      'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 320,  'unit' => 'pack'],
            ['name' => 'MTR Ready-to-Eat Upma',             'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 280,  'unit' => 'pack'],
            ['name' => 'Sunfeast Dark Fantasy',             'category' => 'unhealthy', 'type' => 'readymade', 'calories' => 160,  'unit' => 'pack'],
            ['name' => 'Bournvita (With Milk)',             'category' => 'unhealthy', 'type' => 'drink',     'calories' => 160,  'unit' => 'cup'],
            ['name' => 'Horlicks (With Milk)',              'category' => 'unhealthy', 'type' => 'drink',     'calories' => 150,  'unit' => 'cup'],
            ['name' => 'Complan (With Milk)',               'category' => 'unhealthy', 'type' => 'drink',     'calories' => 170,  'unit' => 'cup'],

        ];

        foreach ($items as $item) {
            \App\Models\FoodItem::firstOrCreate(['name' => $item['name']], $item);
        }
    }
}
